package reception;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alexandrabutoi
 */
public class AppointmentsPanel extends javax.swing.JPanel {

    /**
     * Creates new form SwitchCalendarsPanel
     */
    public AppointmentsPanel() {
        initComponents();
    }

    /**
     * @return the calendarPanel1
     */
    public CalendarPanel getCalendarPanel1() {
        return calendarPanel1;
    }

    /**
     * @param calendarPanel1
     *            the calendarPanel1 to set
     */
    public void setCalendarPanel1(CalendarPanel calendarPanel1) {
        this.calendarPanel1 = calendarPanel1;
    }

    /**
     * @return the calendarPanel2
     */
    public CalendarPanel getCalendarPanel2() {
        return calendarPanel2;
    }

    /**
     * @param calendarPanel2
     *            the calendarPanel2 to set
     */
    public void setCalendarPanel2(CalendarPanel calendarPanel2) {
        this.calendarPanel2 = calendarPanel2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        calendarPanel1 = new CalendarPanel(true);
        calendarPanel2 = new CalendarPanel(false);

        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.addTab("Dentist", calendarPanel1);
        jTabbedPane1.addTab("Hygienist", calendarPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                        .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CalendarPanel calendarPanel1;
    private CalendarPanel calendarPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
