package reception;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Component;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Date;
import java.text.ParseException;
import java.util.ArrayList;

import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

import connection.BackEndRead;
import connection.BackEndWrite;
import types.Address;
import types.people.Patient;

/**
 *
 * @author alexandrabutoi
 */
public class FindPatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form FindPatientPanel
     */
    public FindPatientPanel(ModifyPatientPanel modifyPanel) {
        this.modifyPanel = modifyPanel;
        initComponents();
        model = (DefaultTableModel) jTable1.getModel();

    }

    private void displayPatients(ArrayList<Patient> patients) {

        for (Patient p : patients) {

            int id = p.getId();
            String firstName = p.getName();
            String surname = p.getSurname();
            Date dob = p.getDob();
            String postcode = p.getAddress().getPostcode();
            String phone = p.getPhoneNumber();
            String healthCarePlan = p.getPlanName();
            Object[] row = { id, firstName, surname, dob, postcode, phone, healthCarePlan };
            model.addRow(row);

        }
        repaint();

    }

    private String getFirstName() {
        return nameTextField.getText();
    }

    private String getSurname() {
        return surnameTextField.getText();
    }
    
    public void cleanTable() {
        for (int i = 0; i < model.getRowCount(); i++) {
            for (int j = 0; j < model.getColumnCount(); j++) {
                
                model.setValueAt("", i, j);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        findAppLabel = new javax.swing.JLabel();
        FindAppButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        surnameTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                mousePressedActionPerformed(e);
            }
        });

        setBackground(new java.awt.Color(255, 255, 255));

        findAppLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        findAppLabel.setText("Find Patient");

        FindAppButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        FindAppButton.setText("Find Patient");

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        surnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameTextFieldActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        FindAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    findPatButtonActionPerformed(evt);
                } catch (ParseException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {}, new String[] { "ID", "First Name",
                "Last Name", "Date of Birth", "Address", "Phone number", "Healthcare Plan" }));
        jTable1.setEnabled(false);
        jTable1.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE).addComponent(jScrollPane1,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout
                        .createSequentialGroup().addGap(102, 102, 102).addComponent(jScrollPane1,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(105, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup().addGap(67, 67, 67).addComponent(jLabel1).addGap(18, 18, 18)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addGap(39, 39, 39).addComponent(FindAppButton,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup().addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup().addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(findAppLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addComponent(jPanel1,
                        javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup().addGap(64, 64, 64).addComponent(findAppLabel).addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2).addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(FindAppButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)));
    }// </editor-fold>//GEN-END:initComponents

    private void mousePressedActionPerformed(MouseEvent e) {
        Point p = e.getPoint();
        int row = jTable1.rowAtPoint(p);
        if (patients != null) {
            this.modifyPanel.setPatient(patients.get(row));
            setVisible(false);
            this.modifyPanel.setVisible(true);
            System.out.println("Get " + row + " patient");
        }

    }

    private void surnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_surnameTextFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_surnameTextFieldActionPerformed

    private void findPatButtonActionPerformed(java.awt.event.ActionEvent evt) throws ParseException {// GEN-FIRST:event_regPatientButtonActionPerformed
        // TODO add your handling code here:
        // System.exit(0);
        cleanTable();
        repaint();
        BackEndRead read = new BackEndRead();
        this.patients = read.getPatientList(getFirstName(), getSurname());
        displayPatients(patients);

        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FindAppButton;
    private javax.swing.JLabel findAppLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField surnameTextField;
    private DefaultTableModel model;
    private ArrayList<Patient> patients;
    private ModifyPatientPanel modifyPanel;

    // End of variables declaration//GEN-END:variables
}
